---
framework: jest
preRun:
  command:
    - yarn
postMerge:
  env:
    NODE_ENV: development
    npm_lifecycle_event: test
  pattern:
    - "{packages,scripts}/**/__tests__/*{.js,.coffee,[!d].ts}"
configFile: scripts/jest/config.source-www.js
nodeVersion: 14.17.6
version: 1.0
